org.gradle.jvmargs=-Xmx3G -Xms3G -Duser.language=en

org.gradle.configuration-cache=false

minecraft_version=26.1.2
supported_version=26.1.X
forgified_fabric_api_version=0.154.0+3.1.0+26.1.2

archives_base_name=PinTooltips
mod_version=26.0.2
release_type=release
mod_id=pin_tooltips
mod_name=Pin Tooltips
mod_description=Add the ability to pin tooltips to the screen and view more information from them such as enchantment and mob effect descriptions.
