org.gradle.jvmargs=-Xmx3G -Xms3G -Duser.language=en

# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.1
supported_version=26.1.X
archive_minecraft_version=26.1
loader_version=0.18.4
loom_version=1.14-SNAPSHOT

# Mod Properties
mod_version=26.0.2
release_type=release
mod_id=pin_tooltips
maven_group=snownee.pintooltips
archives_base_name=PinTooltips

# Dependencies
fabric_api_version=0.144.1+26.1
cloth_config_version=19.0.147
# https://modrinth.com/mod/modmenu/versions
modmenu_version=18.0.0-alpha.7
rei_version=20.0.811
jei_version=24.0.0.2
tr_energy_version=5.0.0
jade_version=26.0.4
kiwi_version=26.0.2