org.gradle.jvmargs=-Xmx3G -Xms3G -Duser.language=en -Dnet.minecraftforge.gradle.check.certs=false

org.gradle.configuration-cache=false

minecraft_version=26.1.2
supported_version=26.1.x

archives_base_name=PinTooltips
mod_version=26.0.1
release_type=beta
mod_id=pin_tooltips
mod_name=Pin Tooltips
mod_description=Add the ability to pin tooltips to the screen and view more information from them such as enchantment and mob effect descriptions.