modLoader="javafml"
loaderVersion="[4,)"

license="All Rights Reserved"
issueTrackerURL="${source}/issues"

[[mods]]
modId="pin_tooltips"
version="${version}"
displayName="Pin Tooltips"
displayURL="${source}"
logoFile="logo.png"
credits=""
authors="Snownee, SettingDust"
description='''
${description}
'''

[[mixins]]
config="pin_tooltips.mixins.json"

[[dependencies.pin_tooltips]]
modId="neoforge"
mandatory=true
versionRange="[21,)"
side="CLIENT"

[[dependencies.pin_tooltips]]
modId="minecraft"
mandatory=true
versionRange="[1.21,)"
side="CLIENT"

[[dependencies.pin_tooltips]]
modId="fabric_api"
mandatory=true
versionRange="[0.92,)"
side="CLIENT"

[[dependencies.pin_tooltips]]
modId="more_enchantment_info"
type="optional"
versionRange="[0.2,)"
side="CLIENT"